In [1]:
import pandas as pd 
import numpy as np

In [3]:
data = pd.read_csv("../Assets/Data/202401-citibike-tripdata_1.csv")
data = data.dropna(axis= 0)
print(data.describe())

start_data = data.filter(["ride_id", "rideable_type", "started_at","start_station_name","start_station_id","start_lat","start_lng","member_casual"],axis= 1)
start_data.rename(columns={"started_at": "time", "start_station_name": "station_name", "start_station_id" :"station_id",
                "start_lat": "lat", "start_lng" : "lng"},inplace=True)
start_data["state"] = 0
end_data = data.filter(["ride_id", "rideable_type", "ended_at","end_station_name","end_station_id","end_lat","end_lng","member_casual"],axis= 1)
end_data.rename(columns={"ended_at": "time", "end_station_name": "station_name", "end_station_id" :"station_id",
                "end_lat": "lat", "end_lng" : "lng"},inplace=True)
end_data["state"] = 1
data = pd.concat([start_data,end_data])

data["lat"] = (data["lat"] - np.min(data["lat"]))/(np.max(data["lat"]) - np.min(data["lat"]))
data["lng"] = (data["lng"] - np.min(data["lng"]))/(np.max(data["lng"]) - np.min(data["lng"]))

print(np.min(data["lat"]))
print(np.max(data["lat"]))
print(np.min(data["lng"]))
print(np.max(data["lng"]))
data["time"] = pd.to_datetime(data['time'])
data = data.sort_values(by='time')
data

C:\Users\jaime\AppData\Local\Temp\ipykernel_33084\856000675.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../Assets/Data/202401-citibike-tripdata_1.csv")

           start_lat      start_lng        end_lat        end_lng
count  996600.000000  996600.000000  996600.000000  996600.000000
mean       40.739367     -73.971116      40.739255     -73.971289
std         0.040725       0.028638       0.040562       0.028613
min        40.633385     -74.050656      40.633385     -74.066921
25%        40.714690     -73.991475      40.714740     -73.991600
50%        40.739713     -73.978984      40.739445     -73.979013
75%        40.763126     -73.954823      40.762288     -73.954823
max        40.886300     -73.849780      40.886300     -73.849780
0.0
1.0
0.0
1.0

,ride_id,rideable_type,time,station_name,station_id,lat,lng,member_casual,state
37475,BD613F756C39C4D0,classic_bike,2023-12-31 13:50:28.976,N 12 St & Bedford Ave,5450.04,0.345623,0.516134,casual,0
46904,4B080070FD50B858,electric_bike,2023-12-31 14:55:38.927,W 37 St & 5 Ave,6398.06,0.462587,0.384686,member,0
263997,24F86164747D9B56,classic_bike,2023-12-31 14:57:39.538,Madison St & Montgomery St,5262.09,0.315288,0.377989,casual,0
845934,165867F584717117,classic_bike,2023-12-31 15:57:36.402,Cadman Plaza E & Red Cross Pl,4821.06,0.263063,0.355544,member,0
885791,7FA2408E227974A4,classic_bike,2023-12-31 17:32:19.418,Central Park S & 6 Ave,6876.04,0.523988,0.417146,casual,0
...,...,...,...,...,...,...,...,...,...
993945,8517694D58A7BFF6,classic_bike,2024-01-31 23:57:53.162,Parade Pl & Crooke Ave,3376.02,0.072997,0.468235,member,1
961854,F6CC0E7D69E0AC14,electric_bike,2024-01-31 23:59:25.219,Windsor Pl & 8 Ave,3620.02,0.108815,0.386141,member,1
937175,FF5497A5A844C851,electric_bike,2024-01-31 23:59:28.329,W 190 St & Broadway,8474.02,0.882124,0.616885,member,1
934664,DBD5F1EDA05272A2,classic_bike,2024-01-31 23:59:37.157,W Broadway & Spring St,5569.06,0.362026,0.300553,member,1
939323,6CA27967F8C6F7BF,electric_bike,2024-01-31 23:59:56.370,E 3 St & 1 Ave,5553.03,0.360960,0.364219,member,1

In [11]:
data = data.reindex(["ride_id","rideable_type","time", "station_name", "station_id", "member_casual","lat","lng", "state"],axis = 1)
data.to_csv("../Assets/Data/Event_Data.csv", index=False)